# Generated by Django 4.1 on 2022-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_message_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
